// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwrUT1ohBcFkVufIsLkgPm6wGgilTx8w4',
    appId: '1:374153464225:web:b35765d0eee0e685b4a3e0',
    messagingSenderId: '374153464225',
    projectId: 'event-app-4b387',
    authDomain: 'event-app-4b387.firebaseapp.com',
    storageBucket: 'event-app-4b387.firebasestorage.app',
    measurementId: 'G-XWLMNKJ1Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jq5rzmK2QUfS1VKBgVTa4Qg3OXEAkBY',
    appId: '1:374153464225:android:74e09a66463b92d4b4a3e0',
    messagingSenderId: '374153464225',
    projectId: 'event-app-4b387',
    storageBucket: 'event-app-4b387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqf9pKHFIirGddQ2eSyWUOYv-WHYwfHQM',
    appId: '1:374153464225:ios:1489e7f3aa852746b4a3e0',
    messagingSenderId: '374153464225',
    projectId: 'event-app-4b387',
    storageBucket: 'event-app-4b387.firebasestorage.app',
    iosBundleId: 'com.example.eventparty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqf9pKHFIirGddQ2eSyWUOYv-WHYwfHQM',
    appId: '1:374153464225:ios:1489e7f3aa852746b4a3e0',
    messagingSenderId: '374153464225',
    projectId: 'event-app-4b387',
    storageBucket: 'event-app-4b387.firebasestorage.app',
    iosBundleId: 'com.example.eventparty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwrUT1ohBcFkVufIsLkgPm6wGgilTx8w4',
    appId: '1:374153464225:web:02c28b22b0d6d63eb4a3e0',
    messagingSenderId: '374153464225',
    projectId: 'event-app-4b387',
    authDomain: 'event-app-4b387.firebaseapp.com',
    storageBucket: 'event-app-4b387.firebasestorage.app',
    measurementId: 'G-WVK5S4SZ5N',
  );
}
